version: "3"
services:
  # db:
  #   container_name: postgres
  #   image: postgres
  #   ports:
  #     - '5432:5432'
  # redis:
  #   container_name: redis
  #   image: redis
  web:
    build: .
    # links:
    #   - 'redis:redis'
    # depends_on:
    #     - db
    #     - redis
    ports:
      - '8080:8080'
    # env_file:
    #   - .env